require linux.inc

DESCRIPTION = "Linux kernel"
KERNEL_IMAGETYPE = "uImage"

COMPATIBLE_MACHINE = "(beaglebone)"

# The main PR is now using MACHINE_KERNEL_PR, for omap3 see conf/machine/include/omap3.inc
MACHINE_KERNEL_PR_append = "a"

FILESPATH =. "${FILE_DIRNAME}/linux-mainline-3.7:${FILE_DIRNAME}/linux-mainline-3.7/${MACHINE}:"

S = "${WORKDIR}/git"

PV = "3.7.0"


SRCREV_pn-${PN} = "29594404d7fe73cd80eaa4ee8c43dcc53970c60e"

SRC_URI = " \
	git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git;branch=master \
	file://dma/0001-video-st7735fb-add-st7735-framebuffer-driver.patch \
	file://dma/0002-regulator-tps65910-fix-BUG_ON-shown-with-vrtc-regula.patch \
	file://dma/0003-dmaengine-add-helper-function-to-request-a-slave-DMA.patch \
	file://dma/0004-of-Add-generic-device-tree-DMA-helpers.patch \
	file://dma/0005-of-dma-fix-build-break-for-CONFIG_OF.patch \
	file://dma/0006-of-dma-fix-typos-in-generic-dma-binding-definition.patch \
	file://dma/0007-dmaengine-fix-build-failure-due-to-missing-semi-colo.patch \
	file://dma/0008-dmaengine-edma-fix-slave-config-dependency-on-direct.patch \
	file://dma/0009-ARM-davinci-move-private-EDMA-API-to-arm-common.patch \
	file://dma/0010-ARM-edma-remove-unused-transfer-controller-handlers.patch \
	file://dma/0011-ARM-edma-add-DT-and-runtime-PM-support-for-AM33XX.patch \
	file://dma/0012-ARM-edma-add-AM33XX-crossbar-event-support.patch \
	file://dma/0013-dmaengine-edma-enable-build-for-AM33XX.patch \
	file://dma/0014-dmaengine-edma-Add-TI-EDMA-device-tree-binding.patch \
	file://dma/0015-ARM-dts-add-AM33XX-EDMA-support.patch \
	file://dma/0016-dmaengine-add-dma_request_slave_channel_compat.patch \
	file://dma/0017-mmc-omap_hsmmc-convert-to-dma_request_slave_channel_.patch \
	file://dma/0018-mmc-omap_hsmmc-limit-max_segs-with-the-EDMA-DMAC.patch \
	file://dma/0019-mmc-omap_hsmmc-add-generic-DMA-request-support-to-th.patch \
	file://dma/0020-ARM-dts-add-AM33XX-MMC-support.patch \
	file://dma/0021-spi-omap2-mcspi-convert-to-dma_request_slave_channel.patch \
	file://dma/0022-spi-omap2-mcspi-add-generic-DMA-request-support-to-t.patch \
	file://dma/0023-ARM-dts-add-AM33XX-SPI-support.patch \
	file://dma/0024-Documentation-bindings-add-spansion.patch \
	file://dma/0025-ARM-dts-add-BeagleBone-Adafruit-1.8-LCD-support.patch \
	file://dma/0026-misc-add-gpevt-driver.patch \
	file://dma/0027-ARM-dts-add-BeagleBone-gpevt-support.patch \
	file://dma/0028-ARM-configs-working-AM33XX-edma-dmaengine-defconfig.patch \
	file://dma/0029-ARM-configs-working-da850-edma-dmaengine-defconfig.patch \
	file://dma/0030-misc-gpevt-null-terminate-the-of_match_table.patch \
	file://dma/0031-proposed-probe-fix-works-for-me-on-evm.patch \
	file://cpsw/0001-ARM-OMAP3-hwmod-Add-AM33XX-HWMOD-data-for-davinci_md.patch \
	file://cpsw/0002-net-davinci_mdio-Fix-type-mistake-in-calling-runtime.patch \
	file://cpsw/0003-net-cpsw-Add-parent-child-relation-support-between-c.patch \
	file://cpsw/0004-arm-dts-am33xx-Add-cpsw-and-mdio-module-nodes-for-AM.patch \
	file://pinctrl/0001-i2c-pinctrl-ify-i2c-omap.c.patch \
	file://pinctrl/0002-arm-dts-AM33XX-Configure-pinmuxs-for-user-leds-contr.patch \
	file://pinctrl/0003-beaglebone-DT-set-default-triggers-for-LEDS.patch \
	file://pinctrl/0004-beaglebone-add-a-cpu-led-trigger.patch \
	file://cpufreq/0001-arm-dts-AM33XX-Add-device-tree-OPP-table.patch \
	file://cpufreq/0002-am33xx-DT-add-commented-out-OPP-values-for-ES2.0.patch \
	file://adc/0001-input-TSC-ti_tscadc-Correct-register-usage.patch \
	file://adc/0002-input-TSC-ti_tscadc-Add-Step-configuration-as-platfo.patch \
	file://adc/0003-input-TSC-ti_tscadc-set-FIFO0-threshold-Interrupt.patch \
	file://adc/0004-input-TSC-ti_tscadc-Remove-definition-of-End-Of-Inte.patch \
	file://adc/0005-input-TSC-ti_tscadc-Rename-the-existing-touchscreen-.patch \
	file://adc/0006-MFD-ti_tscadc-Add-support-for-TI-s-TSC-ADC-MFDevice.patch \
	file://adc/0007-input-TSC-ti_tsc-Convert-TSC-into-a-MFDevice.patch \
	file://adc/0008-IIO-ADC-tiadc-Add-support-of-TI-s-ADC-driver.patch \
	file://adc/0009-input-ti_am335x_tsc-Make-steps-enable-configurable.patch \
	file://adc/0010-input-ti_am335x_tsc-Order-of-TSC-wires-connect-made-.patch \
	file://adc/0011-input-ti_am335x_tsc-Add-variance-filters.patch \
	file://adc/0012-ti_tscadc-Update-with-IIO-map-interface-deal-with-pa.patch \
	file://adc/0013-ti_tscadc-Match-mfd-sub-devices-to-regmap-interface.patch \
	file://pwm/0001-ARM-OMAP3-hwmod-Corrects-resource-data-for-PWM-devic.patch \
	file://pwm/0002-pwm_backlight-Add-device-tree-support-for-Low-Thresh.patch \
	file://pwm/0003-pwm-pwm-tiecap-Add-device-tree-binding-support-in-AP.patch \
	file://pwm/0004-Control-module-EHRPWM-clk-enabling.patch \
	file://pwm/0005-pwm-pwm-tiecap-Enable-clock-gating.patch \
	file://pwm/0006-PWM-ti-ehrpwm-fix-up-merge-conflict.patch \
	file://pwm/0007-pwm-pwm_test-Driver-support-for-PWM-module-testing.patch \
	file://pwm/0008-arm-dts-DT-support-for-EHRPWM-and-ECAP-device.patch \
	file://pwm/0009-pwm-pwm-tiehrpwm-Add-device-tree-binding-support-EHR.patch \
	file://pwm/0010-ARM-OMAP2-PWM-limit-am33xx_register_ehrpwm-to-soc_is.patch \
	file://i2c/0001-pinctrl-pinctrl-single-must-be-initialized-early.patch \
	file://i2c/0002-Bone-DTS-working-i2c2-i2c3-in-the-tree.patch \
	file://i2c/0003-am33xx-Convert-I2C-from-omap-to-am33xx-names.patch \
	file://i2c/0004-beaglebone-fix-backlight-entry-in-DT.patch \
	file://usb/0001-Shut-up-musb.patch \
	file://usb/0002-musb-Fix-crashes-and-other-weirdness.patch \
	file://usb/0003-musb-revert-parts-of-032ec49f.patch \
	file://usb/0004-usb-musb-dsps-get-the-PHY-using-phandle-api.patch \
	file://usb/0005-drivers-usb-otg-add-device-tree-support-to-otg-libra.patch \
	file://usb/0006-usb-otg-nop-add-dt-support.patch \
	file://usb/0007-usb-musb-dsps-add-phy-control-logic-to-glue.patch \
	file://usb/0008-usb-musb-dsps-enable-phy-control-for-am335x.patch \
	file://usb/0009-ARM-am33xx-fix-mem-regions-in-USB-hwmod.patch \
	file://da8xx-fb/0001-omap2-clk-Add-missing-lcdc-clock-definition.patch \
	file://da8xx-fb/0002-da8xx-Allow-use-by-am33xx-based-devices.patch \
	file://da8xx-fb/0003-da8xx-Fix-revision-check-on-the-da8xx-driver.patch \
	file://da8xx-fb/0004-da8xx-De-constify-members-in-the-platform-config.patch \
	file://da8xx-fb/0005-da8xx-Add-standard-panel-definition.patch \
	file://da8xx-fb/0006-da8xx-Add-CDTech_S035Q01-panel-used-by-LCD3-bone-cap.patch \
	file://da8xx-fb/0007-da8xx-fb-add-panel-definition-for-beaglebone-LCD7-ca.patch \
	file://da8xx-fb/0008-video-da8xx-fb-fb_check_var-enhancement.patch \
	file://da8xx-fb/0009-video-da8xx-fb-clk_get-on-connection-id-fck.patch \
	file://mmc/0001-mmc-omap_hsmmc-Enable-HSPE-bit-for-high-speed-cards.patch \
	file://mmc/0002-am33xx.dtsi-enable-MMC-HSPE-bit-for-all-3-controller.patch \
	file://mmc/0003-omap-hsmmc-Correct-usage-of-of_find_node_by_name.patch \
	file://fixes/0001-ARM-AM33XX-hwmod-Remove-wrong-INIT_NO_RESET-IDLE-fla.patch \
	file://f2fs/0001-f2fs-add-document.patch \
	file://f2fs/0002-f2fs-add-on-disk-layout.patch \
	file://f2fs/0003-f2fs-add-superblock-and-major-in-memory-structure.patch \
	file://f2fs/0004-f2fs-add-super-block-operations.patch \
	file://f2fs/0005-f2fs-add-checkpoint-operations.patch \
	file://f2fs/0006-f2fs-add-node-operations.patch \
	file://f2fs/0007-f2fs-add-segment-operations.patch \
	file://f2fs/0008-f2fs-add-file-operations.patch \
	file://f2fs/0009-f2fs-add-address-space-operations-for-data.patch \
	file://f2fs/0010-f2fs-add-core-inode-operations.patch \
	file://f2fs/0011-f2fs-add-inode-operations-for-special-inodes.patch \
	file://f2fs/0012-f2fs-add-core-directory-operations.patch \
	file://f2fs/0013-f2fs-add-xattr-and-acl-functionalities.patch \
	file://f2fs/0014-f2fs-add-garbage-collection-functions.patch \
	file://f2fs/0015-f2fs-add-recovery-routines-for-roll-forward.patch \
	file://f2fs/0016-f2fs-update-Kconfig-and-Makefile.patch \
	file://f2fs/0017-f2fs-gc.h-make-should_do_checkpoint-inline.patch \
	file://f2fs/0018-f2fs-move-statistics-code-into-one-file.patch \
	file://f2fs/0019-f2fs-move-proc-files-to-debugfs.patch \
	file://f2fs/0020-f2fs-compile-fix.patch \
	file://6lowpan/0001-6lowpan-lowpan_is_iid_16_bit_compressable-does-not-d.patch \
	file://6lowpan/0002-6lowpan-next-header-is-not-properly-set-upon-decompr.patch \
	file://6lowpan/0003-6lowpan-always-enable-link-layer-acknowledgments.patch \
	file://6lowpan/0004-mac802154-turn-on-ACK-when-enabled-by-the-upper-laye.patch \
	file://6lowpan/0005-6lowpan-use-short-IEEE-802.15.4-addresses-for-broadc.patch \
	file://6lowpan/0006-6lowpan-fix-first-fragment-FRAG1-handling.patch \
	file://6lowpan/0007-6lowpan-store-fragment-tag-values-per-device-instead.patch \
	file://6lowpan/0008-6lowpan-obtain-IEEE802.15.4-sequence-number-from-the.patch \
	file://6lowpan/0009-6lowpan-add-a-new-parameter-in-sysfs-to-turn-on-off-.patch \
	file://6lowpan/0010-6lowpan-use-the-PANID-provided-by-the-device-instead.patch \
	file://6lowpan/0011-6lowpan-modify-udp-compression-uncompression-to-matc.patch \
	file://6lowpan/0012-6lowpan-make-memory-allocation-atomic-during-6lowpan.patch \
	file://6lowpan/0013-mac802154-make-mem-alloc-ATOMIC-to-prevent-schedulin.patch \
	file://6lowpan/0014-mac802154-remove-unnecessary-spinlocks.patch \
	file://6lowpan/0015-mac802154-re-introduce-MAC-primitives-required-to-se.patch \
	file://6lowpan/0016-serial-initial-import-of-the-IEEE-802.15.4-serial-dr.patch \
	file://capebus/0001-i2c-EEPROM-Export-memory-accessor.patch \
	file://capebus/0002-omap-Export-omap_hwmod_lookup-omap_device_build-omap.patch \
	file://capebus/0003-gpio-keys-Pinctrl-fy.patch \
	file://capebus/0004-tps65217-Allow-placement-elsewhere-than-parent-mfd-d.patch \
	file://capebus/0005-pwm-export-of_pwm_request.patch \
	file://capebus/0006-i2c-Export-capability-to-probe-devices.patch \
	file://capebus/0007-pwm-backlight-Pinctrl-fy.patch \
	file://capebus/0008-spi-Export-OF-interfaces-for-capebus-use.patch \
	file://capebus/0009-w1-gpio-Pinctrl-fy.patch \
	file://capebus/0010-w1-gpio-Simplify-get-rid-of-defines.patch \
	file://capebus/0011-arm-dt-Enable-DT-proc-updates.patch \
	file://capebus/0012-ARM-CUSTOM-Build-a-uImage-with-dtb-already-appended.patch \
	file://capebus/0013-beaglebone-create-a-shared-dtsi-for-beaglebone-based.patch \
	file://capebus/0014-beaglebone-enable-emmc-for-bonelt.patch \
	file://capebus/0015-da8xx-dt-Create-da8xx-DT-adapter-device.patch \
	file://capebus/0016-ti-tscadc-dt-Create-ti-tscadc-dt-DT-adapter-device.patch \
	file://capebus/0017-capebus-Core-capebus-support.patch \
	file://capebus/0018-capebus-Add-beaglebone-board-support.patch \
	file://capebus/0019-capebus-Beaglebone-generic-cape-support.patch \
	file://capebus/0020-capebus-Beaglebone-geiger-cape-support.patch \
	file://capebus/0021-capebus-Beaglebone-capebus-DT-update.patch \
	file://capebus/0022-capebus-Document-DT-bindings.patch \
	file://capebus/0023-capebus-Documentation-capebus-summary.patch \
	file://capebus/0024-beaglebone-Update-default-config-for-capebus.patch \
	file://capebus/0025-capebus-Geiger-Cape-config-bugfixs.patch \
	file://capebus/0026-am335x-bone-Add-spi0-pins-defines.patch \
	file://capebus/0027-Allow-more-than-one-instance-of-generic-devices.patch \
	file://capebus/0028-Mark-the-device-as-PRIVATE.patch \
	file://capebus/0029-DT-overlay.patch \
	file://capebus/0030-Bug-fixes-pinctl-gpio-reset.patch \
	file://capebus/0031-ARM-HSMMC-fix-error-path-when-no-gpio_reset.patch \
	file://capebus/0032-capebus-Add-PRUSS-DT-bindings.patch \
	file://hdmi/0001-Import-working-HDMI-driver-from-3.2-kernel.patch \
	file://hdmi/0002-Added-DT-binding-to-NXP-driver.patch \
	file://hdmi/0003-da8xx-fb-Add-timings-for-720x480-60.patch \
	file://hdmi/0004-Add-capebus-override-and-pinmux-for-da8xx-dt.patch \
	file://hdmi/0005-video-Kconfig-Makefile-Add-new-Kconfig-for-old-drive.patch \
	file://hdmi/0006-am335x-bonelt-dts-Add-DT-node-to-probe-NXP-driver.patch \
	file://hdmi/0007-tda-driver-enable-1280x720.patch \
	file://hdmi/0008-Makefile-Disable-CEC.patch \
	file://pruss/0001-uio-uio_pruss-port-to-AM33xx.patch \
	file://pruss/0002-ARM-omap-add-DT-support-for-deasserting-hardware-res.patch \
	file://pruss/0003-ARM-dts-AM33xx-PRUSS-support.patch \
	file://arm/0001-kbuild-deb-pkg-set-host-machine-after-dpkg-gencontro.patch \
	file://arm/0002-arm-add-definition-of-strstr-to-decompress.c.patch \
	file://omap/0001-mach-omap2-board-igep0020.c-Fix-reboot-problem.patch \
	file://omap_sakoman/0001-OMAP-DSS2-add-bootarg-for-selecting-svideo.patch \
	file://omap_sakoman/0002-video-add-timings-for-hd720.patch \
	file://omap_beagle_expansion/0001-Beagle-expansion-add-buddy-param-for-expansionboard-.patch \
	file://omap_beagle_expansion/0002-Beagle-expansion-add-zippy.patch \
	file://omap_beagle_expansion/0003-Beagle-expansion-add-zippy2.patch \
	file://omap_beagle_expansion/0004-Beagle-expansion-add-trainer.patch \
	file://omap_beagle_expansion/0005-Beagle-expansion-add-CircuitCo-ulcd-Support.patch \
	file://omap_beagle_expansion/0006-Beagle-expansion-add-wifi.patch \
	file://omap_beagle_expansion/0007-Beagle-expansion-add-beaglefpga.patch \
	file://omap_beagle_expansion/0008-Beagle-expansion-add-spidev.patch \
	file://omap_beagle_expansion/0009-Beagle-expansion-add-Aptina-li5m03-camera.patch \
	file://omap_beagle_expansion/0010-Beagle-expansion-add-LSR-COM6L-Adapter-Board.patch \
	file://omap_beagle/0001-meego-modedb-add-Toshiba-LTA070B220F-800x480-support.patch \
	file://omap_beagle/0002-backlight-Add-TLC59108-backlight-control-driver.patch \
	file://omap_beagle/0003-tlc59108-adjust-for-beagleboard-uLCD7.patch \
	file://omap_beagle/0004-zeroMAP-Open-your-eyes.patch \
	file://omap_beagle/0005-TEMP-Beagle-xM-cpufreq-disable-800Mhz-opp.patch \
	file://omap_beagle/0006-ARM-OMAP-Beagle-C4-fix-reboot-problem.patch \
	file://omap_panda/0001-panda-fix-wl12xx-regulator.patch \
	file://omap_panda/0002-ti-st-st-kim-fixing-firmware-path.patch \
	file://omap_sgx/0001-Revert-drm-kill-drm_sman.patch \
	file://omap_fixes/0001-omap3-Increase-limit-on-bootarg-mpurate.patch \
	file://omap_thermal/0001-staging-omap-thermal-fix-compilation.patch \
	file://omap_thermal/0002-staging-omap-thermal-remove-platform-data-nomenclatu.patch \
	file://omap_thermal/0003-staging-omap-thermal-remove-freq_clip-table.patch \
	file://omap_thermal/0004-staging-omap-thermal-add-IRQ-debugging-messaging.patch \
	file://omap_thermal/0005-staging-omap-thermal-fix-context-restore-function.patch \
	file://net/0001-Attempted-SMC911x-BQL-patch.patch \
	file://spi/0001-spi-spidev-Add-device-tree-bindings.patch \
	file://defconfig \
"
